import type { NodeRole } from "./types";

export const MESH_TUNING = {
  // Global caps and solve cadence.
  network: {
    maxNodes: 2600,
    maxLinks: 4000,
    maxVisibleNodes: 1500,
    maxVisibleLinks: 3600,
    solveIntervalMs: 220,
    spatialHashCellSizeDeg: 2.4,
  },
  // Visible hemisphere culling relative to camera and projection mode.
  visibility: {
    planeOffsetPerspective: -0.31,
    planeOffsetOrtho: -0.31,
  },
  // Role-level population mix and per-role rendering/interaction scale.
  roles: {
    split: {
      cluster: 0.54,
      person: 0.15,
      bridge: 0.01,
      mover: 0.30,
    } satisfies Record<NodeRole, number>,
    linkBudgets: {
      cluster: [2, 3],
      person: [1, 3],
      bridge: [3, 5],
      mover: [2, 3],
    } satisfies Record<NodeRole, readonly [number, number]>,
    linkRangesDeg: {
      cluster: [1.4, 2.8],
      person: [1.0, 1.9],
      bridge: [2.8, 5.5],
      mover: [1.8, 4.0],
    } satisfies Record<NodeRole, readonly [number, number]>,
    driftAmplitudeDeg: {
      cluster: [0.0, 0.0],
      person: [0.015, 0.08],
      bridge: [0.04, 0.28],
      mover: [0.03, 0.12],
    } satisfies Record<NodeRole, readonly [number, number]>,
    sizeMultipliers: {
      cluster: [0.86, 1.14],
      person: [0.72, 0.95],
      bridge: [0.95, 1.26],
      mover: [0.74, 1.02],
    } satisfies Record<NodeRole, readonly [number, number]>,
    alphaMultipliers: {
      cluster: [0.9, 1.04],
      person: [0.8, 0.94],
      bridge: [0.94, 1.08],
      mover: [0.82, 0.98],
    } satisfies Record<NodeRole, readonly [number, number]>,
  },
  // Distribution and initial placement.
  spawn: {
    remoteClusterChance: 0.25,
    remoteClusterGroupsBase: 1,
    remoteClusterGroupsScale: 4,
    remoteClusterSeedSpreadDeg: [0.25, 0.85],
    remoteClusterRadiusDeg: [0.12, 0.42],
    remoteClusterInterconnectDistanceDeg: 5.5,
    remoteClusterInterconnectCount: [1, 2],
    clusterHotspotSpreadDeg: [0.85, 1.35],
    personHotspotSpreadDeg: [0.25, 0.62],
    remoteFieldSpreadDeg: [0.45, 0.95],
    clusterBlendChance: 0.42,
    personBlendChance: 0.18,
    clusterBlendMix: [0.16, 0.42],
    personBlendMix: [0.08, 0.22],
    clusterBlendSpreadDeg: [0.55, 1.0],
    personBlendSpreadDeg: [0.16, 0.42],
    bridgeAnchorProgress: [0.12, 0.76],
    bridgeLaneOffsetScale: 0.75,
    bridgeCurveJitter: 0.06,
    moverLaneWeightThicknessBias: 0.7,
    moverLaneOffsetScale: 0.55,
    moverCurveBias: 0.12,
    moverInitialDwellChance: 0.08,
    moverDwellMs: [500, 1800],
    densitySizeScaleBase: 0.92,
    densitySizeScaleWeight: 0.18,
    activityBase: 0.28,
    densityActivityWeight: 0.44,
    roleActivityBoost: {
      cluster: 0,
      person: 0.04,
      bridge: 0.08,
      mover: 0.12,
    } satisfies Record<NodeRole, number>,
    activityNoise: 0.1,
    pulseRateRange: {
      cluster: [0.38, 1.1],
      person: [0.38, 1.25],
      bridge: [0.5, 1.55],
      mover: [0.42, 1.9],
    } satisfies Record<NodeRole, readonly [number, number]>,
    clusterStructuralLinksPerNode: [2, 4],
    clusterStructuralMaxDistanceDeg: 2.8,
    clusterStructuralStrength: [0.42, 0.88],
    moverSpeeds: {
      ground_vehicle: [0.05, 0.11],
      drone: [0.08, 0.16],
      aircraft: [0.12, 0.22],
      wearable_device: [0.06, 0.11],
      personal_device: [0.06, 0.13],
      default: [0.04, 0.09],
    },
  },
  // Per-frame drift, mover pacing, and activity response.
  motion: {
    personRetargetDelayMs: [700, 3200],
    personInitialRetargetDelayMs: [500, 2600],
    personRetargetResponse: 3.4,
    personMoveSpeed: 0.44,
    personAltitudePulseAmplitude: 0.0022,
    personAltitudePulseMix: [0.5, 0.28],
    clusterRetargetDelayMs: [350, 2400],
    clusterInitialRetargetDelayMs: [300, 2200],
    clusterRetargetResponse: 4.6,
    clusterMoveSpeed: 0.72,
    clusterAltitudePulseAmplitude: 0.003,
    clusterAltitudePulseMix: [0.6, 0.4],
    bridgeLaneSpanBase: 0.035,
    bridgeLaneSpanDriftScale: 0.22,
    bridgeLaneDriftSpeedBase: 0.03,
    bridgeLaneDriftActivityScale: 0.02,
    bridgeRetargetResponse: 5.2,
    bridgeMoveSpeed: 0.8,
    bridgeAltitudeBaseOffset: 0.004,
    bridgeAltitudePulseAmplitude: 0.0035,
    bridgeAltitudePulseMix: [0.5, 0.5],
    moverDestinationLerp: 2.4,
    moverNextConnectedLaneChance: 0.86,
    moverAltitudeBaseOffset: 0.006,
    moverAltitudePulseAmplitude: 0.005,
    moverAltitudePulseMix: [0.7, 0.3],
    moverCurveBiasRange: 0.12,
    energyLerpSpeed: 3.4,
    roleEnergyBias: {
      cluster: 0.42,
      person: 0.48,
      bridge: 0.54,
      moverIdle: 0.48,
      moverMoving: 0.62,
    },
    hotspotEnergyWeight: 0.28,
    pulseEnergyAmplitude: 0.06,
  },
  // Local mesh churn and bridge persistence.
  links: {
    ttlMs: {
      local: [1200, 4500],
      bridge: [3500, 9000],
    },
    solveWindowMultiplier: 4,
    eligibleRefreshRatio: [0.2, 0.3],
    scoreWeights: {
      proximity: 0.64,
      sameHotspot: 0.18,
      sameRegion: 0.08,
      crossRegionPenalty: -0.03,
      clusterPersonBias: 0.12,
      bridgeBias: 0.14,
      moverBias: 0.06,
      retained: 0.18,
      noise: 0.08,
    },
    bridgeKindDistanceThresholdDeg: 2.8,
    pinnedBridgeDistanceThresholdDeg: 1.6,
    anglePenalty: {
      hardThresholdDeg: 14,
      hardValue: 0.16,
      softThresholdDeg: 28,
      softValue: 0.06,
    },
    strengthClamp: [0.18, 1.0],
    activeLinkCutoff: {
      targetStrength: 0.04,
      fade: 0.06,
    },
    hiddenLinkCutoff: {
      targetStrength: 0.03,
      fade: 0.03,
    },
    decay: {
      pinnedStrengthRetain: 0.45,
      bridgeEasing: 3.2,
      localEasing: 5.8,
      bridgeFadeIn: 1.4,
      localFadeIn: 2.6,
      bridgeFadeOut: 0.8,
      localFadeOut: 1.8,
    },
  },
  // Final render intensity and point/line brightness.
  render: {
    nodeAlphaRoleBoost: {
      cluster: 0.84,
      person: 0.78,
      bridge: 0.9,
      mover: 1.04,
    } satisfies Record<NodeRole, number>,
    nodeAlphaBase: 0.58,
    nodeAlphaActivityWeight: 0.4,
    nodeAlphaClamp: [0.08, 1.0],
    linkAlpha: {
      localBase: 0.06,
      localStrengthWeight: 0.28,
      localMax: 0.38,
      bridgeBase: 0.07,
      bridgeStrengthWeight: 0.18,
      pinnedBridgeStrengthWeight: 0.22,
      bridgeMax: 0.28,
      pinnedBridgeMax: 0.34,
    },
    pointSize: {
      distanceScale: 10,
      minPerspectiveDepth: 2,
      minPixels: 1.4,
      maxPixels: 12,
      pulseAmplitude: 0.12,
    },
  },
} as const;
