#!/usr/bin/env python3
"""
Bake the globe's land mask into src/lib/og/land.ts, for the link previews
drawn at build time (src/lib/og/art.ts), where there's no image decoder.

Reads the green channel of public/globe-field-2048.webp (the land mask —
scripts/bake-globe-field.py packs it there), downsamples it to 1440 × 720
equirectangular, and writes it as a base64 bitset, row-major, MSB first.

Run from the repo root after re-baking the globe field:
  python3 scripts/bake-og-land.py
Needs Pillow.
"""

import base64
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
W, H = 1440, 720


def main() -> None:
    field = Image.open(ROOT / "public/globe-field-2048.webp").convert("RGB")
    green = field.getchannel("G").resize((W, H), Image.BILINEAR)
    px = green.load()
    bits = bytearray((W * H + 7) // 8)
    land = 0
    for y in range(H):
        for x in range(W):
            if px[x, y] > 127:
                i = y * W + x
                bits[i >> 3] |= 0x80 >> (i & 7)
                land += 1
    data = base64.b64encode(bytes(bits)).decode()
    out = ROOT / "src/lib/og/land.ts"
    out.write_text(
        "/**\n"
        " * The globe's land mask, 1440 × 720 equirectangular (row 0 at 90° N,\n"
        " * column 0 at 180° W), as a base64 bitset, MSB first. Generated by\n"
        " * scripts/bake-og-land.py from public/globe-field-2048.webp — do not edit.\n"
        " */\n"
        f"export const LAND = {{ w: {W}, h: {H}, bits: \"{data}\" }};\n"
    )
    print(f"{land / (W * H):.1%} land → {out.relative_to(ROOT)} ({len(data) // 1024} KB)")


if __name__ == "__main__":
    main()
