#!/usr/bin/env python3
"""
Extract the glyphs the sovereign OS watch face draws from its BDF fonts into a
TypeScript module, so the browser re-creation uses the firmware's own pixels.

    python3 scripts/bdf-to-glyphs.py ~/workspaces/sovereign/font src/lib/watch/glyphs.ts

The firmware (components/st7789/fontbdf.c) loads each font into memory and
draws a glyph from its BBX and BITMAP rows only — DWIDTH is ignored, and the
pen advances by BBX width + 2. It also sizes every string by the BBX of '2'.
Both are kept here: `w h yo` per glyph, the rows as hex, and `ref` = '2'.
"""
import os
import sys

FONTS = {"small": "MPFW12_C.bdf", "medium": "MPFW32_C.bdf", "large": "MPFW52_C.bdf"}
CHARS = "0123456789.%AHMOPSegionrsv"


def parse(path):
    glyphs, cur, rows = {}, None, None
    for line in open(path, encoding="latin-1"):
        parts = line.split()
        if not parts:
            continue
        key = parts[0]
        if key == "STARTCHAR":
            cur = {}
        elif key == "ENCODING" and cur is not None:
            cur["code"] = int(parts[1])
        elif key == "BBX" and cur is not None:
            cur["w"], cur["h"], cur["xo"], cur["yo"] = map(int, parts[1:5])
        elif key == "BITMAP" and cur is not None:
            rows = []
        elif key == "ENDCHAR" and cur is not None:
            cur["rows"] = rows or []
            glyphs[cur["code"]] = cur
            cur, rows = None, None
        elif rows is not None:
            rows.append(parts[0])
    return glyphs


def main(font_dir, out):
    lines = [
        "/**",
        " * Glyphs from the sovereign OS fonts (ProFontWindows, rasterised by",
        " * FontForge to BDF at 17, 44 and 72 px). Generated by",
        " * scripts/bdf-to-glyphs.py — do not edit by hand.",
        " *",
        " * Per glyph: BBX width, height and y-offset, then the BITMAP rows as hex,",
        " * most significant bit first. `ref` is the glyph the firmware sizes strings by.",
        " */",
        "export interface Glyph {",
        "  w: number;",
        "  h: number;",
        "  yo: number;",
        "  rows: string[];",
        "}",
        "",
        "export interface BdfFont {",
        "  ref: { w: number; h: number };",
        "  glyphs: Record<string, Glyph>;",
        "}",
        "",
    ]
    for name, file in FONTS.items():
        glyphs = parse(os.path.join(os.path.expanduser(font_dir), file))
        two = glyphs[ord("2")]
        lines.append(f"export const {name.upper()}: BdfFont = {{")
        lines.append(f"  ref: {{ w: {two['w']}, h: {two['h']} }},")
        lines.append("  glyphs: {")
        missing = []
        for ch in CHARS:
            g = glyphs.get(ord(ch))
            if not g:
                missing.append(ch)
                continue
            rows = ", ".join(f'"{r}"' for r in g["rows"])
            key = ch if ch.isalnum() else repr(ch)
            key = f'"{ch}"'
            lines.append(f"    {key}: {{ w: {g['w']}, h: {g['h']}, yo: {g['yo']}, rows: [{rows}] }},")
        lines.append("  },")
        lines.append("};")
        lines.append("")
        print(f"{file}: {len(CHARS) - len(missing)} glyphs, ref '2' {two['w']}x{two['h']}, missing {missing!r}")
    open(out, "w").write("\n".join(lines))
    print(f"-> {out} ({os.path.getsize(out) / 1024:.1f} KB)")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(*sys.argv[1:])
