#!/usr/bin/env python3
"""
Bake the colormaps Avi's fractal code used into src/lib/fractals/palettes.ts.

Each palette is 256 RGB entries, stored as base64 so the shader can take them
as one texture (a row per palette). The cmasher maps are read from the text
files cmasher ships (the Fractals project's venv has them); the others come
from matplotlib. Row 0 is the site's own ramp, ink to bone.

    python3 scripts/palettes-to-ts.py ~/PycharmProjects/Fractals/venv/lib/python3.11/site-packages/cmasher/colormaps
"""
import base64
import os
import sys

import numpy as np
from matplotlib import colormaps

CMR = os.path.expanduser(sys.argv[1]) if len(sys.argv) > 1 else "."
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "fractals", "palettes.ts")

INK = np.array([10, 10, 11]) / 255
BONE = np.array([230, 228, 223]) / 255


def cmr(name):
    table = np.loadtxt(os.path.join(CMR, f"cm_{name}.txt"))
    idx = np.linspace(0, len(table) - 1, 256)
    return np.stack([np.interp(idx, np.arange(len(table)), table[:, k]) for k in range(3)], 1)


def mpl(name):
    return colormaps[name](np.linspace(0, 1, 256))[:, :3]


PALETTES = [
    ("site", "ink to bone — the site's own tone", INK + (BONE - INK) * np.linspace(0, 1, 256)[:, None]),
    ("bone", "matplotlib bone — Thorn", mpl("bone")),
    ("inferno", "matplotlib inferno — the early Julia sets", mpl("inferno")),
    ("sunburst", "cmasher sunburst — the video's Mandelbrot and Julia", cmr("sunburst")),
    ("gothic", "cmasher gothic — the Thomas basins", cmr("gothic")),
    ("twilight", "matplotlib twilight_shifted — the Lorenz basins", mpl("twilight_shifted")),
    ("ember", "cmasher ember — the rotated Lorenz slices", cmr("ember")),
    ("magma", "matplotlib magma — DeepJulia's z^5 and the complex Collatz", mpl("magma")),
    ("prism", "matplotlib prism — Newton's method on sin z / z (COS_2LOW)", mpl("prism")),
    ("lilac", "cmasher lilac — Julia_3, c = -0.76 + 0.0838i", cmr("lilac")),
    ("ocean", "cmasher ocean — Iterate.py's list", cmr("ocean")),
    ("horizon", "cmasher horizon — Iterate.py's list", cmr("horizon")),
    ("arctic_r", "cmasher arctic, reversed — JULIA_SIN", cmr("arctic")[::-1]),
    ("bubblegum", "cmasher bubblegum — X3_1, the second root", cmr("bubblegum")),
    ("gem", "cmasher gem — X3_1, the third root", cmr("gem")),
]

lines = [
    "// Generated by scripts/palettes-to-ts.py — do not edit.",
    "// The colormaps Avi's fractal code used, 256 RGB entries each, base64.",
    "",
    "export const PALETTES = [",
]
for name, note, rgb in PALETTES:
    data = base64.b64encode(np.round(np.clip(rgb, 0, 1) * 255).astype(np.uint8).tobytes()).decode()
    lines.append(f'  /* {note} */ {{ id: "{name}", data: "{data}" }},')
lines += [
    "] as const;",
    "",
    "export type PaletteId = (typeof PALETTES)[number][\"id\"];",
    "",
    "export const PALETTE_ROW: Record<PaletteId, number> = Object.fromEntries(",
    "  PALETTES.map((p, i) => [p.id, i])",
    ") as Record<PaletteId, number>;",
    "",
]
with open(OUT, "w") as f:
    f.write("\n".join(lines))
print("wrote", OUT, len(PALETTES), "palettes")
